// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';
import {main} from '../models';

export function GetDevices():Promise<Array<server.Device>>;

export function GetLogs():Promise<Array<string>>;

export function GetStats():Promise<main.Stats>;

export function Greet(arg1:string):Promise<string>;

export function MinimizeWindow():Promise<void>;

export function Quit():Promise<void>;

export function ShowWindow():Promise<void>;
