// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {server} from '../models';
import {main} from '../models';

export function DomReady(arg1:context.Context):Promise<void>;

export function GetDeviceEvents(arg1:number):Promise<Array<server.Event>>;

export function GetDevices():Promise<Array<server.Device>>;

export function GetGlobalEvents():Promise<Array<server.GlobalEvent>>;

export function GetLogs():Promise<Array<string>>;

export function GetStats():Promise<main.Stats>;

export function Greet(arg1:string):Promise<string>;

export function MinimizeWindow():Promise<void>;

export function Quit():Promise<void>;

export function ShowWindow():Promise<void>;

export function StartEmitter(arg1:context.Context):Promise<void>;

export function StartLogsEmitter(arg1:context.Context):Promise<void>;

export function StartStatsEmitter(arg1:context.Context):Promise<void>;
