// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DomReady(arg1) {
  return window['go']['main']['App']['DomReady'](arg1);
}

export function GetDeviceEvents(arg1) {
  return window['go']['main']['App']['GetDeviceEvents'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetGlobalEvents() {
  return window['go']['main']['App']['GetGlobalEvents']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartEmitter(arg1) {
  return window['go']['main']['App']['StartEmitter'](arg1);
}

export function StartLogsEmitter(arg1) {
  return window['go']['main']['App']['StartLogsEmitter'](arg1);
}

export function StartStatsEmitter(arg1) {
  return window['go']['main']['App']['StartStatsEmitter'](arg1);
}
